# fly.toml app configuration file generated for graphmlcopy on 2023-09-15T02:04:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "graphmlcopy"
primary_region = "sea"

[build]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
